version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5433'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=supertal-test

  supertal-backend:
    container_name: supertal-backend
    build:
      context: .
    command: bash -c "npm run start:dev"
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgresql

volumes:
  postgres_data:
